In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import OneHotEncoder
from category_encoders import TargetEncoder
from sklearn.preprocessing import MinMaxScaler

%config IPCompleter.greedy=True

In [12]:
ruta_proyecto = 'C:/Users/mcana/OneDrive/Escritorio/PORTAFOLIO/ML/LEAD_SCORINGLEAD_SCORING_PROYECTO'

In [13]:
nombre_cat = 'cat_resultado_calidad.pickle'
nombre_num = 'num_resultado_calidad.pickle'

In [14]:
cat = pd.read_pickle(ruta_proyecto + '/Datos/tabajo/' + nombre_cat)
num = pd.read_pickle(ruta_proyecto + '/Datos/tabajo/' + nombre_num)

In [16]:
num

,compra,visitas_total,tiempo_en_site_total,paginas_vistas_visita,score_actividad,score_perfil
id,,,,,,
660737,0,0,0,0.0,15.0,15.0
660728,0,5,674,2.5,15.0,15.0
660719,0,1,305,1.0,13.0,17.0
660681,1,2,1428,1.0,15.0,18.0
660680,0,0,0,0.0,17.0,15.0
...,...,...,...,...,...,...
579697,1,8,1016,4.0,15.0,20.0
579642,0,2,1770,2.0,14.0,20.0
579615,1,5,210,2.5,14.0,20.0
579538,1,3,499,3.0,15.0,16.0
579533,1,6,1279,3.0,15.0,18.0

In [17]:
cat

,origen,fuente,ult_actividad,ambito,ocupacion,descarga_lm
id,,,,,,
660737,API,Chat,Page Visited on Website,Select,Unemployed,No
660728,API,Organic Search,Email Opened,Select,Unemployed,No
660719,Landing Page Submission,Direct Traffic,OTROS,Media and Advertising,Unemployed,No
660681,Landing Page Submission,Google,Converted to Lead,Select,Unemployed,No
660680,API,Chat,Chat Conversation,Select,Unemployed,No
...,...,...,...,...,...,...
579697,Landing Page Submission,Google,Email Opened,"Banking, Investment And Insurance",Unemployed,No
579642,Landing Page Submission,Direct Traffic,SMS Sent,Human Resource Management,Unemployed,Yes
579615,Landing Page Submission,Direct Traffic,SMS Sent,Business Administration,Unemployed,No
579538,Landing Page Submission,Google,SMS Sent,Human Resource Management,Unemployed,No
579533,Landing Page Submission,Direct Traffic,SMS Sent,Supply Chain Management,Unemployed,Yes

### One Hot Encoding

In [21]:
#variables
var_ohe = ['origen', 'fuente','ult_actividad','ambito','ocupacion','descarga_lm']
ohe = OneHotEncoder(sparse_output= False, handle_unknown='ignore')

In [25]:
cat_ohe = ohe.fit_transform(cat[var_ohe])

In [26]:
cat_ohe = pd.DataFrame(cat_ohe, columns= ohe.get_feature_names_out())

##### en cuanto a las numÃ©ricas no vamos a hacer ninguna transformaciÃ³n.

In [29]:
num.shape

(5114, 6)

In [28]:
pd.concat([cat_ohe, num.reset_index()], axis = 1)

,origen_API,origen_Landing Page Submission,origen_Lead Add Form,origen_OTROS,fuente_Chat,fuente_Direct Traffic,fuente_Google,fuente_OTROS,fuente_Organic Search,fuente_Reference,...,ocupacion_Working Professional,descarga_lm_No,descarga_lm_Yes,id,compra,visitas_total,tiempo_en_site_total,paginas_vistas_visita,score_actividad,score_perfil
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,660737,0,0,0,0.0,15.0,15.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,660728,0,5,674,2.5,15.0,15.0
2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,660719,0,1,305,1.0,13.0,17.0
3,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,660681,1,2,1428,1.0,15.0,18.0
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,660680,0,0,0,0.0,17.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5109,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,579697,1,8,1016,4.0,15.0,20.0
5110,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,579642,0,2,1770,2.0,14.0,20.0
5111,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,579615,1,5,210,2.5,14.0,20.0
5112,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,579538,1,3,499,3.0,15.0,16.0
5113,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,579533,1,6,1279,3.0,15.0,18.0

In [30]:
df = pd.concat([cat_ohe, num.reset_index()], axis = 1)

## VARIABLES A REESCALAR CON MIN-MAX

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5114 entries, 0 to 5113
Data columns (total 44 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   origen_API                                5114 non-null   float64
 1   origen_Landing Page Submission            5114 non-null   float64
 2   origen_Lead Add Form                      5114 non-null   float64
 3   origen_OTROS                              5114 non-null   float64
 4   fuente_Chat                               5114 non-null   float64
 5   fuente_Direct Traffic                     5114 non-null   float64
 6   fuente_Google                             5114 non-null   float64
 7   fuente_OTROS                              5114 non-null   float64
 8   fuente_Organic Search                     5114 non-null   float64
 9   fuente_Reference                          5114 non-null   float64
 10  ult_actividad_Chat Conversation           5114 non-null   float64
 11  ult_actividad_Converted to Lead           5114 non-null   float64
 12  ult_actividad_Email Link Clicked          5114 non-null   float64
 13  ult_actividad_Email Opened                5114 non-null   float64
 14  ult_actividad_OTROS                       5114 non-null   float64
 15  ult_actividad_Page Visited on Website     5114 non-null   float64
 16  ult_actividad_SMS Sent                    5114 non-null   float64
 17  ambito_Banking, Investment And Insurance  5114 non-null   float64
 18  ambito_Business Administration            5114 non-null   float64
 19  ambito_Finance Management                 5114 non-null   float64
 20  ambito_Healthcare Management              5114 non-null   float64
 21  ambito_Human Resource Management          5114 non-null   float64
 22  ambito_IT Projects Management             5114 non-null   float64
 23  ambito_International Business             5114 non-null   float64
 24  ambito_Marketing Management               5114 non-null   float64
 25  ambito_Media and Advertising              5114 non-null   float64
 26  ambito_OTROS                              5114 non-null   float64
 27  ambito_Operations Management              5114 non-null   float64
 28  ambito_Select                             5114 non-null   float64
 29  ambito_Supply Chain Management            5114 non-null   float64
 30  ambito_Travel and Tourism                 5114 non-null   float64
 31  ocupacion_OTROS                           5114 non-null   float64
 32  ocupacion_Student                         5114 non-null   float64
 33  ocupacion_Unemployed                      5114 non-null   float64
 34  ocupacion_Working Professional            5114 non-null   float64
 35  descarga_lm_No                            5114 non-null   float64
 36  descarga_lm_Yes                           5114 non-null   float64
 37  id                                        5114 non-null   int64
 38  compra                                    5114 non-null   int64
 39  visitas_total                             5114 non-null   Int64
 40  tiempo_en_site_total                      5114 non-null   int64
 41  paginas_vistas_visita                     5114 non-null   float64
 42  score_actividad                           5114 non-null   float64
 43  score_perfil                              5114 non-null   float64
dtypes: Int64(1), float64(40), int64(3)
memory usage: 1.7 MB

In [32]:
var_mms= df.iloc[:,39:].columns

In [33]:
var_mms

Index(['visitas_total', 'tiempo_en_site_total', 'paginas_vistas_visita',
       'score_actividad', 'score_perfil'],
      dtype='object')

In [36]:
mms = MinMaxScaler()

In [37]:
df_mms = mms.fit_transform(df[var_mms])

##### Guardar como DataFrame

In [38]:
nombres_mms = [variable + '_mms' for variable in var_mms]

df_mms = pd.DataFrame(df_mms, columns = nombres_mms)

# UNIFICAR DATASETS REESCALADOS

In [58]:
target = num[['compra']].copy().reset_index(drop=True)

In [59]:
id = df.id

In [65]:
pd.concat([id, cat_ohe,df_mms, target], axis=1)

,id,origen_API,origen_Landing Page Submission,origen_Lead Add Form,origen_OTROS,fuente_Chat,fuente_Direct Traffic,fuente_Google,fuente_OTROS,fuente_Organic Search,...,ocupacion_Unemployed,ocupacion_Working Professional,descarga_lm_No,descarga_lm_Yes,visitas_total_mms,tiempo_en_site_total_mms,paginas_vistas_visita_mms,score_actividad_mms,score_perfil_mms,compra
0,660737,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.00,0.000000,0.000,0.727273,0.444444,0
1,660728,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.10,0.296655,0.125,0.727273,0.444444,0
2,660719,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.02,0.134243,0.050,0.545455,0.666667,0
3,660681,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.04,0.628521,0.050,0.727273,0.777778,1
4,660680,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.00,0.000000,0.000,0.909091,0.444444,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5109,579697,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.16,0.447183,0.200,0.727273,1.000000,1
5110,579642,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.04,0.779049,0.100,0.636364,1.000000,0
5111,579615,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.10,0.092430,0.125,0.636364,1.000000,1
5112,579538,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.06,0.219630,0.150,0.727273,0.555556,1
5113,579533,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.12,0.562940,0.150,0.727273,0.777778,1

In [66]:
pd.concat([id, cat_ohe,df_mms, target], axis=1).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5114 entries, 0 to 5113
Data columns (total 44 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   id                                        5114 non-null   int64
 1   origen_API                                5114 non-null   float64
 2   origen_Landing Page Submission            5114 non-null   float64
 3   origen_Lead Add Form                      5114 non-null   float64
 4   origen_OTROS                              5114 non-null   float64
 5   fuente_Chat                               5114 non-null   float64
 6   fuente_Direct Traffic                     5114 non-null   float64
 7   fuente_Google                             5114 non-null   float64
 8   fuente_OTROS                              5114 non-null   float64
 9   fuente_Organic Search                     5114 non-null   float64
 10  fuente_Reference                          5114 non-null   float64
 11  ult_actividad_Chat Conversation           5114 non-null   float64
 12  ult_actividad_Converted to Lead           5114 non-null   float64
 13  ult_actividad_Email Link Clicked          5114 non-null   float64
 14  ult_actividad_Email Opened                5114 non-null   float64
 15  ult_actividad_OTROS                       5114 non-null   float64
 16  ult_actividad_Page Visited on Website     5114 non-null   float64
 17  ult_actividad_SMS Sent                    5114 non-null   float64
 18  ambito_Banking, Investment And Insurance  5114 non-null   float64
 19  ambito_Business Administration            5114 non-null   float64
 20  ambito_Finance Management                 5114 non-null   float64
 21  ambito_Healthcare Management              5114 non-null   float64
 22  ambito_Human Resource Management          5114 non-null   float64
 23  ambito_IT Projects Management             5114 non-null   float64
 24  ambito_International Business             5114 non-null   float64
 25  ambito_Marketing Management               5114 non-null   float64
 26  ambito_Media and Advertising              5114 non-null   float64
 27  ambito_OTROS                              5114 non-null   float64
 28  ambito_Operations Management              5114 non-null   float64
 29  ambito_Select                             5114 non-null   float64
 30  ambito_Supply Chain Management            5114 non-null   float64
 31  ambito_Travel and Tourism                 5114 non-null   float64
 32  ocupacion_OTROS                           5114 non-null   float64
 33  ocupacion_Student                         5114 non-null   float64
 34  ocupacion_Unemployed                      5114 non-null   float64
 35  ocupacion_Working Professional            5114 non-null   float64
 36  descarga_lm_No                            5114 non-null   float64
 37  descarga_lm_Yes                           5114 non-null   float64
 38  visitas_total_mms                         5114 non-null   float64
 39  tiempo_en_site_total_mms                  5114 non-null   float64
 40  paginas_vistas_visita_mms                 5114 non-null   float64
 41  score_actividad_mms                       5114 non-null   float64
 42  score_perfil_mms                          5114 non-null   float64
 43  compra                                    5114 non-null   int64
dtypes: float64(42), int64(2)
memory usage: 1.7 MB

In [67]:
pd.concat([id, cat_ohe,df_mms, target], axis=1).isna().sum()

id                                          0
origen_API                                  0
origen_Landing Page Submission              0
origen_Lead Add Form                        0
origen_OTROS                                0
fuente_Chat                                 0
fuente_Direct Traffic                       0
fuente_Google                               0
fuente_OTROS                                0
fuente_Organic Search                       0
fuente_Reference                            0
ult_actividad_Chat Conversation             0
ult_actividad_Converted to Lead             0
ult_actividad_Email Link Clicked            0
ult_actividad_Email Opened                  0
ult_actividad_OTROS                         0
ult_actividad_Page Visited on Website       0
ult_actividad_SMS Sent                      0
ambito_Banking, Investment And Insurance    0
ambito_Business Administration              0
ambito_Finance Management                   0
ambito_Healthcare Management                0
ambito_Human Resource Management            0
ambito_IT Projects Management               0
ambito_International Business               0
ambito_Marketing Management                 0
ambito_Media and Advertising                0
ambito_OTROS                                0
ambito_Operations Management                0
ambito_Select                               0
ambito_Supply Chain Management              0
ambito_Travel and Tourism                   0
ocupacion_OTROS                             0
ocupacion_Student                           0
ocupacion_Unemployed                        0
ocupacion_Working Professional              0
descarga_lm_No                              0
descarga_lm_Yes                             0
visitas_total_mms                           0
tiempo_en_site_total_mms                    0
paginas_vistas_visita_mms                   0
score_actividad_mms                         0
score_perfil_mms                            0
compra                                      0
dtype: int64

In [69]:
df_tablon = pd.concat([id, cat_ohe,df_mms, target], axis=1).set_index('id')

In [70]:
ruta_df_tablon = ruta_proyecto + '/Datos/Tabajo/' + 'df_tablon.pickle'

In [71]:
df_tablon.to_pickle(ruta_df_tablon)